// frontend/src/app/admin/settings/page.tsx
'use client';

import { useEffect, useRef, useState } from 'react';
import { adminGetSettings, adminUpdateSettings, adminExportSettings, adminImportSettings, SystemSettings, FeatureItem } from '@/lib/api';
import { Toast, useToast } from '@/components/Toast';

type Section = 'llm' | 'pricing' | 'afdian' | 'email' | 'app';

const TABS: { id: Section; label: string; desc: string }[] = [
  { id: 'llm',     label: '🤖 AI 模型',   desc: '配置 AI 分析使用的模型和 API 密钥' },
  { id: 'pricing', label: '💰 定价展示',  desc: '用户看到的套餐价格、每日次数及功能介绍' },
  { id: 'afdian',  label: '💳 爱发电',    desc: '配置爱发电支付套餐 ID、收款链接及 API 凭证' },
  { id: 'email',   label: '📧 邮件服务',  desc: '注册验证邮件的发送配置（Resend.com）' },
  { id: 'app',     label: '⚙️ 应用信息',  desc: '站点名称等基础配置' },
];

function Field({
  label, hint, children,
}: { label: string; hint?: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: '1.25rem' }}>
      <label style={{ display: 'block', fontWeight: 600, fontSize: '0.875rem', marginBottom: '0.35rem' }}>
        {label}
      </label>
      {children}
      {hint && <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginTop: '0.3rem' }}>{hint}</p>}
    </div>
  );
}

function Input({ value, onChange, type = 'text', placeholder }: {
  value: string | number; onChange: (v: string) => void;
  type?: string; placeholder?: string;
}) {
  return (
    <input
      type={type}
      value={value}
      onChange={e => onChange(e.target.value)}
      placeholder={placeholder}
      style={{
        width: '100%', padding: '0.5rem 0.75rem', border: '1px solid var(--border)',
        borderRadius: '0.375rem', background: 'var(--background)', color: 'var(--foreground)',
        fontSize: '0.875rem', boxSizing: 'border-box',
      }}
    />
  );
}

function NumInput({ value, onChange, min = 0 }: { value: number; onChange: (v: number) => void; min?: number }) {
  return (
    <input
      type="number"
      value={value}
      min={min}
      onChange={e => onChange(Number(e.target.value))}
      style={{
        width: '100%', padding: '0.5rem 0.75rem', border: '1px solid var(--border)',
        borderRadius: '0.375rem', background: 'var(--background)', color: 'var(--foreground)',
        fontSize: '0.875rem', boxSizing: 'border-box',
      }}
    />
  );
}

function SaveButton({ loading, onClick }: { loading: boolean; onClick: () => void }) {
  return (
    <button
      className="btn btn-primary"
      onClick={onClick}
      disabled={loading}
      style={{ marginTop: '1rem', minWidth: '100px' }}
    >
      {loading ? '保存中…' : '💾 保存'}
    </button>
  );
}

function FeatureMatrixEditor({ features, onChange }: {
  features: FeatureItem[];
  onChange: (f: FeatureItem[]) => void;
}) {
  const TIERS = ['free', 'basic', 'premium'] as const;
  const TIER_LABELS = { free: '免费版', basic: '标准版', premium: '专业版' };

  const move = (i: number, dir: -1 | 1) => {
    const j = i + dir;
    if (j < 0 || j >= features.length) return;
    const next = [...features];
    [next[i], next[j]] = [next[j], next[i]];
    onChange(next);
  };

  const remove = (i: number) => onChange(features.filter((_, idx) => idx !== i));

  const updateText = (i: number, text: string) => {
    const next = [...features];
    next[i] = { ...next[i], text };
    onChange(next);
  };

  const toggleTier = (i: number, tier: string) => {
    const next = [...features];
    const tiers = next[i].tiers.includes(tier)
      ? next[i].tiers.filter(t => t !== tier)
      : [...next[i].tiers, tier];
    next[i] = { ...next[i], tiers };
    onChange(next);
  };

  const cellStyle: React.CSSProperties = {
    padding: '0.4rem 0.5rem', borderBottom: '1px solid var(--border)', textAlign: 'center' as const,
  };
  const thStyle: React.CSSProperties = {
    padding: '0.5rem', fontWeight: 600, fontSize: '0.8rem',
    background: 'var(--background)', borderBottom: '2px solid var(--border)', textAlign: 'center' as const,
  };

  return (
    <div style={{ marginBottom: '1.25rem' }}>
      <label style={{ display: 'block', fontWeight: 600, fontSize: '0.875rem', marginBottom: '0.5rem' }}>
        功能矩阵
      </label>
      <p style={{ fontSize: '0.75rem', color: 'var(--muted)', marginBottom: '0.75rem' }}>
        定义所有功能及各版本支持情况，升级页会自动展示每个版本的 ✓ 和 ✗ 列表
      </p>
      <div style={{ overflowX: 'auto', border: '1px solid var(--border)', borderRadius: '0.5rem' }}>
        <table style={{ width: '100%', borderCollapse: 'collapse', minWidth: '480px' }}>
          <thead>
            <tr>
              <th style={{ ...thStyle, textAlign: 'left', paddingLeft: '0.75rem', width: '40%' }}>功能名称</th>
              {TIERS.map(t => <th key={t} style={thStyle}>{TIER_LABELS[t]}</th>)}
              <th style={thStyle}>排序 / 删除</th>
            </tr>
          </thead>
          <tbody>
            {features.map((f, i) => (
              <tr key={i} style={{ background: i % 2 === 0 ? 'transparent' : 'rgba(0,0,0,0.02)' }}>
                <td style={{ ...cellStyle, textAlign: 'left', paddingLeft: '0.75rem' }}>
                  <input
                    value={f.text}
                    onChange={e => updateText(i, e.target.value)}
                    style={{
                      width: '100%', background: 'transparent', border: 'none', outline: 'none',
                      fontSize: '0.875rem', color: 'var(--foreground)',
                    }}
                    placeholder="功能描述"
                  />
                </td>
                {TIERS.map(tier => (
                  <td key={tier} style={cellStyle}>
                    <input
                      type="checkbox"
                      checked={f.tiers.includes(tier)}
                      onChange={() => toggleTier(i, tier)}
                      style={{ cursor: 'pointer', width: '1rem', height: '1rem' }}
                    />
                  </td>
                ))}
                <td style={cellStyle}>
                  <div style={{ display: 'flex', gap: '0.25rem', justifyContent: 'center' }}>
                    <button onClick={() => move(i, -1)} disabled={i === 0}
                      style={{ background: 'none', border: 'none', cursor: i === 0 ? 'default' : 'pointer',
                        color: i === 0 ? 'var(--muted)' : 'var(--foreground)', padding: '0 0.25rem', fontSize: '0.875rem' }}>↑</button>
                    <button onClick={() => move(i, 1)} disabled={i === features.length - 1}
                      style={{ background: 'none', border: 'none', cursor: i === features.length - 1 ? 'default' : 'pointer',
                        color: i === features.length - 1 ? 'var(--muted)' : 'var(--foreground)', padding: '0 0.25rem', fontSize: '0.875rem' }}>↓</button>
                    <button onClick={() => remove(i)}
                      style={{ background: 'none', border: 'none', cursor: 'pointer',
                        color: '#ef4444', padding: '0 0.25rem', fontSize: '0.875rem' }}>✕</button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <button
        onClick={() => onChange([...features, { text: '', tiers: [] }])}
        style={{ marginTop: '0.5rem', background: 'none', border: '1px dashed var(--border)',
          borderRadius: '0.375rem', padding: '0.4rem 1rem', cursor: 'pointer',
          color: 'var(--muted)', fontSize: '0.875rem', width: '100%' }}>
        + 添加功能
      </button>
    </div>
  );
}


export default function AdminSettingsPage() {
  const [activeTab, setActiveTab] = useState<Section>('llm');
  const [cfg, setCfg] = useState<SystemSettings | null>(null);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState<Section | null>(null);
  const [ioWorking, setIoWorking] = useState(false);
  const importRef = useRef<HTMLInputElement>(null);
  const { toast, show: showToast } = useToast();

  useEffect(() => {
    adminGetSettings()
      .then(d => { setCfg(d); setLoading(false); })
      .catch(e => { showToast(e?.response?.data?.detail || '加载失败', 'error'); setLoading(false); });
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const save = async (section: Section, data: Record<string, unknown>) => {
    setSaving(section);
    try {
      await adminUpdateSettings(section, data);
      const updated = await adminGetSettings();
      setCfg(updated);
      showToast('保存成功', 'ok');
    } catch (e: unknown) {
      const err = e as { response?: { data?: { detail?: string } } };
      showToast(err?.response?.data?.detail || '保存失败', 'error');
    } finally {
      setSaving(null);
    }
  };

  const handleExport = async () => {
    setIoWorking(true);
    try {
      const data = await adminExportSettings();
      const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `settings-${new Date().toISOString().slice(0, 10)}.json`;
      a.click();
      URL.revokeObjectURL(url);
      showToast('已导出配置', 'ok');
    } catch (e: unknown) {
      const err = e as { response?: { data?: { detail?: string } } };
      showToast(err?.response?.data?.detail || '导出失败', 'error');
    } finally {
      setIoWorking(false);
    }
  };

  const handleImportFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    e.target.value = '';
    setIoWorking(true);
    try {
      const text = await file.text();
      const data = JSON.parse(text) as SystemSettings;
      await adminImportSettings(data);
      const updated = await adminGetSettings();
      setCfg(updated);
      showToast('配置已导入并生效', 'ok');
    } catch (e: unknown) {
      const err = e as { response?: { data?: { detail?: string } } };
      showToast(err?.response?.data?.detail || '导入失败，请检查 JSON 格式', 'error');
    } finally {
      setIoWorking(false);
    }
  };

  if (loading) return <div style={{ textAlign: 'center', paddingTop: '4rem' }}><div className="spinner" style={{ margin: '0 auto' }} /></div>;
  if (!cfg) return <div className="error">加载设置失败</div>;

  return (
    <div>
      <Toast toast={toast} />

      <div style={{ marginBottom: '1.5rem', display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.75rem' }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', fontWeight: 700 }}>系统设置</h1>
          <p style={{ color: 'var(--muted)', fontSize: '0.875rem' }}>所有修改实时生效，无需重启服务器</p>
        </div>
        <div style={{ display: 'flex', gap: '0.5rem', alignItems: 'center' }}>
          <input ref={importRef} type="file" accept=".json" style={{ display: 'none' }} onChange={handleImportFile} />
          <button
            className="btn"
            onClick={() => importRef.current?.click()}
            disabled={ioWorking}
            style={{ fontSize: '0.8rem', padding: '0.4rem 0.85rem' }}
          >
            📥 导入配置
          </button>
          <button
            className="btn btn-primary"
            onClick={handleExport}
            disabled={ioWorking}
            style={{ fontSize: '0.8rem', padding: '0.4rem 0.85rem' }}
          >
            📤 导出配置
          </button>
        </div>
      </div>

      {/* Tab bar */}
      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginBottom: '1.5rem' }}>
        {TABS.map(t => (
          <button
            key={t.id}
            onClick={() => setActiveTab(t.id)}
            style={{
              padding: '0.5rem 1rem', borderRadius: '0.375rem', border: 'none', cursor: 'pointer',
              fontSize: '0.875rem', fontWeight: activeTab === t.id ? 700 : 400,
              background: activeTab === t.id ? 'var(--primary)' : 'var(--card)',
              color: activeTab === t.id ? '#fff' : 'var(--foreground)',
              boxShadow: activeTab === t.id ? '0 2px 6px rgba(0,0,0,0.15)' : 'none',
            }}
          >
            {t.label}
          </button>
        ))}
      </div>

      {/* Tab description */}
      <p style={{ fontSize: '0.875rem', color: 'var(--muted)', marginBottom: '1.25rem' }}>
        {TABS.find(t => t.id === activeTab)?.desc}
      </p>

      {/* ── LLM ── */}
      {activeTab === 'llm' && (() => {
        const l = cfg.llm;
        return (
          <div className="card">
            <h2 style={{ fontWeight: 600, marginBottom: '1.25rem' }}>AI 模型配置</h2>
            <Field label="提供商 (provider)" hint="支持 openai / deepseek / claude / custom">
              <Input value={l.provider} onChange={v => setCfg({ ...cfg, llm: { ...l, provider: v } })} placeholder="openai" />
            </Field>
            <Field label="API Key" hint="AI 服务商的 API 密钥，留空则使用服务器环境变量">
              <Input value={l.api_key} type="password"
                onChange={v => setCfg({ ...cfg, llm: { ...l, api_key: v } })}
                placeholder="sk-xxxxxxxx" />
            </Field>
            <Field label="Base URL" hint="API 请求地址，使用 OpenAI 兼容接口时填写">
              <Input value={l.base_url} onChange={v => setCfg({ ...cfg, llm: { ...l, base_url: v } })}
                placeholder="https://api.deepseek.com/v1" />
            </Field>
            <Field label="模型名称 (model)">
              <Input value={l.model} onChange={v => setCfg({ ...cfg, llm: { ...l, model: v } })}
                placeholder="deepseek-chat" />
            </Field>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <Field label="最大 Token (max_tokens)" hint="每次请求最多生成的 token 数">
                <NumInput value={l.max_tokens} min={100}
                  onChange={v => setCfg({ ...cfg, llm: { ...l, max_tokens: v } })} />
              </Field>
              <Field label="随机性 (temperature)" hint="0=最稳定，1=最发散，推荐 0.7">
                <Input value={l.temperature} type="number"
                  onChange={v => setCfg({ ...cfg, llm: { ...l, temperature: parseFloat(v) || 0 } })}
                  placeholder="0.7" />
              </Field>
            </div>
            <SaveButton loading={saving === 'llm'} onClick={() => save('llm', cfg.llm as unknown as Record<string, unknown>)} />
          </div>
        );
      })()}

      {/* ── 定价 ── */}
      {activeTab === 'pricing' && (() => {
        const p = cfg.pricing;
        const features: FeatureItem[] = Array.isArray(p.features) ? p.features : [];
        const setFeatures = (f: FeatureItem[]) => setCfg({ ...cfg, pricing: { ...p, features: f } });
        return (
          <div className="card">
            <h2 style={{ fontWeight: 600, marginBottom: '1.25rem' }}>套餐定价展示</h2>
            <Field label="计费周期" hint='显示在价格后的单位，如"月"或"年"'>
              <Input value={p.period} onChange={v => setCfg({ ...cfg, pricing: { ...p, period: v } })} placeholder="月" />
            </Field>
            {/* Free-tier daily limits */}
            <div style={{ border: '1px solid var(--border)', borderRadius: '0.5rem', padding: '1rem', marginBottom: '1rem' }}>
              <p style={{ fontWeight: 600, marginBottom: '0.75rem' }}>免费档每日次数</p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <Field label="游客（未登录）" hint="设备限额，不区分套餐">
                  <NumInput value={p.guest_daily ?? 1} min={0}
                    onChange={v => setCfg({ ...cfg, pricing: { ...p, guest_daily: v } })} />
                </Field>
                <Field label="免费版（已登录）" hint="注册用户免费档每日次数">
                  <NumInput value={p.free_daily ?? 3} min={0}
                    onChange={v => setCfg({ ...cfg, pricing: { ...p, free_daily: v } })} />
                </Field>
              </div>
            </div>
            {(['basic', 'premium'] as const).map(tier => (
              <div key={tier} style={{ border: '1px solid var(--border)', borderRadius: '0.5rem', padding: '1rem', marginBottom: '1rem' }}>
                <p style={{ fontWeight: 600, marginBottom: '0.75rem' }}>{tier === 'basic' ? '标准版' : '专业版'}</p>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                  <Field label="价格（元）" hint="展示在升级页面的数字">
                    <Input value={p[tier].price}
                      onChange={v => setCfg({ ...cfg, pricing: { ...p, [tier]: { ...p[tier], price: v } } })}
                      placeholder={tier === 'basic' ? '19.9' : '49'} />
                  </Field>
                  <Field label="每日次数" hint="实际配额，同步生效">
                    <NumInput value={p[tier].daily} min={1}
                      onChange={v => setCfg({ ...cfg, pricing: { ...p, [tier]: { ...p[tier], daily: v } } })} />
                  </Field>
                </div>
              </div>
            ))}
            <FeatureMatrixEditor features={features} onChange={setFeatures} />
            <SaveButton loading={saving === 'pricing'} onClick={() => save('pricing', cfg.pricing as unknown as Record<string, unknown>)} />
          </div>
        );
      })()}

      {/* ── 爱发电 ── */}
      {activeTab === 'afdian' && (() => {
        const a = cfg.afdian;
        return (
          <div className="card">
            <h2 style={{ fontWeight: 600, marginBottom: '1.25rem' }}>爱发电支付配置</h2>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
              <Field label="标准版套餐 Plan ID" hint="爱发电后台套餐 ID">
                <Input value={a.basic_plan_id} onChange={v => setCfg({ ...cfg, afdian: { ...a, basic_plan_id: v } })} />
              </Field>
              <Field label="专业版套餐 Plan ID">
                <Input value={a.premium_plan_id} onChange={v => setCfg({ ...cfg, afdian: { ...a, premium_plan_id: v } })} />
              </Field>
              <Field label="标准版购买链接" hint="展示给用户的爱发电购买地址">
                <Input value={a.basic_link} onChange={v => setCfg({ ...cfg, afdian: { ...a, basic_link: v } })} placeholder="https://afdian.net/..." />
              </Field>
              <Field label="专业版购买链接">
                <Input value={a.premium_link} onChange={v => setCfg({ ...cfg, afdian: { ...a, premium_link: v } })} placeholder="https://afdian.net/..." />
              </Field>
            </div>
            <div style={{ borderTop: '1px solid var(--border)', paddingTop: '1rem', marginTop: '0.5rem' }}>
              <p style={{ fontWeight: 600, marginBottom: '0.75rem', fontSize: '0.875rem', color: 'var(--muted)' }}>
                🔑 API 凭证（用于主动查询订单）
              </p>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1rem' }}>
                <Field label="创作者 User ID" hint="爱发电开发者后台的用户 ID">
                  <Input value={a.user_id} onChange={v => setCfg({ ...cfg, afdian: { ...a, user_id: v } })} />
                </Field>
                <Field label="API Token" hint="爱发电开发者后台生成的 Token">
                  <Input value={a.api_token} type="password"
                    onChange={v => setCfg({ ...cfg, afdian: { ...a, api_token: v } })} />
                </Field>
              </div>
              <Field label="Webhook Token" hint="用于验证爱发电主动推送的请求是否合法">
                <Input value={a.webhook_token} type="password"
                  onChange={v => setCfg({ ...cfg, afdian: { ...a, webhook_token: v } })} />
              </Field>
            </div>
            <SaveButton loading={saving === 'afdian'} onClick={() => save('afdian', cfg.afdian as unknown as Record<string, unknown>)} />
          </div>
        );
      })()}

      {/* ── 邮件 ── */}
      {activeTab === 'email' && (() => {
        const e = cfg.email;
        return (
          <div className="card">
            <h2 style={{ fontWeight: 600, marginBottom: '1.25rem' }}>邮件服务配置</h2>
            <Field label="Resend API Key" hint="从 resend.com 申请，用于发送注册验证邮件">
              <Input value={e.resend_api_key} type="password"
                onChange={v => setCfg({ ...cfg, email: { ...e, resend_api_key: v } })} placeholder="re_xxxxxxxx" />
            </Field>
            <Field label="前端域名 (APP_BASE_URL)" hint="验证邮件中的链接会带上这个地址">
              <Input value={e.app_base_url} onChange={v => setCfg({ ...cfg, email: { ...e, app_base_url: v } })}
                placeholder="https://yourdomain.com" />
            </Field>
            <SaveButton loading={saving === 'email'} onClick={() => save('email', cfg.email as unknown as Record<string, unknown>)} />
          </div>
        );
      })()}

      {/* ── 应用 ── */}
      {activeTab === 'app' && (() => {
        const a = cfg.app;
        return (
          <div className="card">
            <h2 style={{ fontWeight: 600, marginBottom: '1.25rem' }}>应用基础设置</h2>
            <Field label="站点名称" hint="显示在页面标题、导航栏及邮件中的应用名称">
              <Input value={a.name} onChange={v => setCfg({ ...cfg, app: { name: v } })}
                placeholder="我的AI分析" />
            </Field>
            <SaveButton loading={saving === 'app'} onClick={() => save('app', cfg.app as unknown as Record<string, unknown>)} />
            <hr style={{ margin: '1.5rem 0', borderColor: 'var(--border)' }} />
            <p style={{ fontSize: '0.82rem', color: 'var(--muted)' }}>
              🗂️ 股票名称映射已迁移至 <a href="/admin/market-data" style={{ color: 'var(--primary)' }}>市场数据管理</a> 页面。
            </p>
          </div>
        );
      })()}
    </div>
  );
}

// frontend/pages/admin/settings.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import api from '~/lib/api'

function getAdminHeaders() {
  const token = typeof window !== 'undefined' ? localStorage.getItem('admin_token') : ''
  return { 'X-Admin-Token': token || '' }
}

const activeTab = ref('llm')
const settings = ref<any>({})
const loading = ref(false)
const saving = ref(false)
const msg = ref('')
const msgType = ref<'success' | 'error'>('success')
const fileInput = ref<HTMLInputElement | null>(null)

const tabs = [
  { key: 'llm', label: '🤖 AI 模型' },
  { key: 'pricing', label: '💰 定价展示' },
  { key: 'afdian', label: '💳 爱发电' },
  { key: 'email', label: '📧 邮件服务' },
  { key: 'app', label: '⚙️ 应用信息' },
]

const tiers = ['free', 'basic', 'premium']
const tierLabels: Record<string, string> = { free: '免费版', basic: '标准版', premium: '专业版' }

function showMsg(text: string, type: 'success' | 'error' = 'success') {
  msg.value = text
  msgType.value = type
  setTimeout(() => { msg.value = '' }, 3000)
}

function ensureSection(section: string) {
  if (!settings.value[section]) settings.value[section] = {}
}

function getField(section: string, field: string) {
  ensureSection(section)
  return settings.value[section][field]
}

function setField(section: string, field: string, val: any) {
  ensureSection(section)
  settings.value[section][field] = val
}

function getTierField(tier: string, field: string) {
  if (!settings.value.pricing) settings.value.pricing = {}
  if (!settings.value.pricing[tier]) settings.value.pricing[tier] = {}
  return settings.value.pricing[tier][field]
}

function setTierField(tier: string, field: string, val: any) {
  if (!settings.value.pricing) settings.value.pricing = {}
  if (!settings.value.pricing[tier]) settings.value.pricing[tier] = {}
  settings.value.pricing[tier][field] = val
}

function getFeatures(): { text: string; tiers: string[] }[] {
  if (!settings.value.pricing) settings.value.pricing = {}
  if (!Array.isArray(settings.value.pricing.features)) settings.value.pricing.features = []
  return settings.value.pricing.features
}

function addFeature() {
  getFeatures().push({ text: '', tiers: [] })
}

function removeFeature(i: number) {
  getFeatures().splice(i, 1)
}

function setFeatureText(i: number, v: string) {
  getFeatures()[i].text = v
}

function toggleTier(i: number, tier: string) {
  const f = getFeatures()[i]
  const idx = f.tiers.indexOf(tier)
  if (idx === -1) f.tiers.push(tier)
  else f.tiers.splice(idx, 1)
}

onMounted(async () => {
  loading.value = true
  try {
    const res = await api.get('/api/admin/settings', { headers: getAdminHeaders() })
    settings.value = res.data || {}
  } catch {
    showMsg('❌ 加载失败，请检查 Admin Token', 'error')
  } finally {
    loading.value = false
  }
})

async function saveSettings() {
  saving.value = true
  try {
    await api.put('/api/admin/settings', settings.value, { headers: getAdminHeaders() })
    showMsg('✅ 保存成功', 'success')
  } catch (e: any) {
    const detail = e.response?.data?.detail || '保存失败'
    showMsg(`❌ ${detail}`, 'error')
  } finally {
    saving.value = false
  }
}

async function exportSettings() {
  try {
    const res = await api.get('/api/admin/settings/export', {
      headers: getAdminHeaders(),
      responseType: 'blob',
    })
    const url = URL.createObjectURL(new Blob([res.data], { type: 'application/json' }))
    const a = document.createElement('a')
    a.href = url
    a.download = `settings-${new Date().toISOString().slice(0, 10)}.json`
    a.click()
    URL.revokeObjectURL(url)
    showMsg('✅ 导出成功', 'success')
  } catch {
    showMsg('❌ 导出失败', 'error')
  }
}

function triggerImport() {
  fileInput.value?.click()
}

async function onFileChange(e: Event) {
  const file = (e.target as HTMLInputElement).files?.[0]
  if (!file) return
  const form = new FormData()
  form.append('file', file)
  try {
    await api.post('/api/admin/settings/import', form, {
      headers: { ...getAdminHeaders(), 'Content-Type': 'multipart/form-data' },
    })
    showMsg('✅ 导入成功，重新加载中...', 'success')
    const res = await api.get('/api/admin/settings', { headers: getAdminHeaders() })
    settings.value = res.data || {}
  } catch {
    showMsg('❌ 导入失败', 'error')
  }
  ;(e.target as HTMLInputElement).value = ''
}
</script>

<template>
  <div style="position:fixed;inset:0;background:#f2f2f7;display:flex;flex-direction:column;overflow-y:auto;">

    <!-- Flash message -->
    <Transition name="flash">
      <div
        v-if="msg"
        style="position:fixed;top:16px;right:16px;z-index:9999;padding:10px 18px;border-radius:10px;font-size:14px;font-weight:600;color:#fff;box-shadow:0 4px 16px rgba(0,0,0,0.18);"
        :style="{ background: msgType === 'success' ? '#34c759' : '#ff3b30' }"
      >
        {{ msg }}
      </div>
    </Transition>

    <!-- Header -->
    <div style="display:flex;align-items:center;padding:48px 16px 16px;">
      <NuxtLink to="/admin" style="color:#007aff;text-decoration:none;font-size:15px;">← 返回</NuxtLink>
      <h1 style="flex:1;text-align:center;font-size:17px;font-weight:600;color:#1c1c1e;margin-right:40px;">系统设置</h1>
    </div>

    <div style="padding:0 16px 32px;max-width:720px;margin:0 auto;width:100%;box-sizing:border-box;">

      <!-- Loading -->
      <div v-if="loading" style="display:flex;justify-content:center;padding:48px 0;">
        <div style="width:28px;height:28px;border:3px solid #007aff;border-top-color:transparent;border-radius:50%;animation:spin 0.8s linear infinite;" />
      </div>

      <template v-else>

        <!-- Tab bar -->
        <div style="display:flex;gap:4px;overflow-x:auto;background:#fff;border-radius:12px;padding:6px;margin-bottom:16px;-webkit-overflow-scrolling:touch;scrollbar-width:none;">
          <button
            v-for="tab in tabs"
            :key="tab.key"
            @click="activeTab = tab.key"
            :style="{
              flex:'none',
              padding:'8px 14px',
              borderRadius:'8px',
              border:'none',
              cursor:'pointer',
              fontSize:'13px',
              fontWeight:'600',
              whiteSpace:'nowrap',
              transition:'background 0.15s,color 0.15s',
              background: activeTab === tab.key ? '#007aff' : 'transparent',
              color: activeTab === tab.key ? '#fff' : '#3c3c43',
            }"
          >
            {{ tab.label }}
          </button>
        </div>

        <!-- Content card -->
        <div style="background:#fff;border-radius:16px;padding:24px;">

          <!-- ===================== LLM TAB ===================== -->
          <template v-if="activeTab === 'llm'">
            <h2 style="font-size:15px;font-weight:700;color:#1c1c1e;margin:0 0 20px;">AI 模型配置</h2>

            <div style="display:flex;flex-direction:column;gap:16px;">
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Provider</label>
                <input
                  type="text"
                  :value="getField('llm','provider')"
                  @input="setField('llm','provider',($event.target as HTMLInputElement).value)"
                  placeholder="openai / deepseek / ..."
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">API Key</label>
                <input
                  type="password"
                  :value="getField('llm','api_key')"
                  @input="setField('llm','api_key',($event.target as HTMLInputElement).value)"
                  placeholder="sk-..."
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Base URL</label>
                <input
                  type="text"
                  :value="getField('llm','base_url')"
                  @input="setField('llm','base_url',($event.target as HTMLInputElement).value)"
                  placeholder="https://api.openai.com/v1"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Model</label>
                <input
                  type="text"
                  :value="getField('llm','model')"
                  @input="setField('llm','model',($event.target as HTMLInputElement).value)"
                  placeholder="gpt-4o / deepseek-chat"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Max Tokens</label>
                <input
                  type="number"
                  :value="getField('llm','max_tokens')"
                  @input="setField('llm','max_tokens',Number(($event.target as HTMLInputElement).value))"
                  placeholder="4096"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Temperature</label>
                <input
                  type="number"
                  step="0.1"
                  min="0"
                  max="2"
                  :value="getField('llm','temperature')"
                  @input="setField('llm','temperature',Number(($event.target as HTMLInputElement).value))"
                  placeholder="0.7"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
            </div>
          </template>

          <!-- ===================== PRICING TAB ===================== -->
          <template v-if="activeTab === 'pricing'">
            <h2 style="font-size:15px;font-weight:700;color:#1c1c1e;margin:0 0 20px;">定价展示配置</h2>

            <div style="display:flex;flex-direction:column;gap:24px;">
              <div v-for="tier in tiers" :key="tier" style="border:1px solid rgba(0,0,0,0.08);border-radius:12px;padding:16px;">
                <h3 style="font-size:14px;font-weight:700;color:#007aff;margin:0 0 14px;">{{ tierLabels[tier] }}</h3>
                <div style="display:flex;flex-direction:column;gap:12px;">
                  <div>
                    <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">每日限额</label>
                    <input
                      type="number"
                      :value="getTierField(tier,'daily_limit')"
                      @input="setTierField(tier,'daily_limit',Number(($event.target as HTMLInputElement).value))"
                      style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                    />
                  </div>
                  <div>
                    <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">价格</label>
                    <input
                      type="text"
                      :value="getTierField(tier,'price')"
                      @input="setTierField(tier,'price',($event.target as HTMLInputElement).value)"
                      placeholder="¥29"
                      style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                    />
                  </div>
                  <div>
                    <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">周期</label>
                    <input
                      type="text"
                      :value="getTierField(tier,'period')"
                      @input="setTierField(tier,'period',($event.target as HTMLInputElement).value)"
                      placeholder="月 / 年"
                      style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                    />
                  </div>
                </div>
              </div>
            </div>

          <!-- Features editor -->
          <div style="margin-top:24px;">
            <div style="display:flex;align-items:center;justify-content:space-between;margin-bottom:12px;">
              <h3 style="font-size:14px;font-weight:700;color:#1c1c1e;margin:0;">功能列表</h3>
              <button
                @click="addFeature"
                style="padding:6px 12px;background:#007aff;color:#fff;border:none;border-radius:8px;font-size:13px;font-weight:600;cursor:pointer;"
              >➕ 添加功能</button>
            </div>
            <div style="display:flex;flex-direction:column;gap:8px;">
              <div
                v-for="(f, i) in getFeatures()"
                :key="i"
                style="display:flex;align-items:center;gap:8px;background:#f9f9fb;border-radius:8px;padding:8px 10px;"
              >
                <input
                  type="text"
                  :value="f.text"
                  @input="setFeatureText(i, ($event.target as HTMLInputElement).value)"
                  placeholder="功能说明"
                  style="flex:1;padding:6px 8px;border-radius:6px;border:1px solid rgba(0,0,0,0.12);font-size:14px;outline:none;"
                />
                <label style="display:flex;align-items:center;gap:4px;font-size:12px;font-weight:600;color:#3c3c43;white-space:nowrap;cursor:pointer;">
                  <input type="checkbox" :checked="f.tiers.includes('basic')" @change="toggleTier(i,'basic')" style="cursor:pointer;" />
                  标准版
                </label>
                <label style="display:flex;align-items:center;gap:4px;font-size:12px;font-weight:600;color:#3c3c43;white-space:nowrap;cursor:pointer;">
                  <input type="checkbox" :checked="f.tiers.includes('premium')" @change="toggleTier(i,'premium')" style="cursor:pointer;" />
                  专业版
                </label>
                <button
                  @click="removeFeature(i)"
                  style="padding:4px 8px;background:#ff3b30;color:#fff;border:none;border-radius:6px;font-size:12px;cursor:pointer;flex-shrink:0;"
                >删除</button>
              </div>
              <p v-if="getFeatures().length === 0" style="font-size:13px;color:#aeaeb2;text-align:center;padding:8px 0;">暂无功能，点击「添加功能」</p>
            </div>
          </div>
          </template>

          <!-- ===================== AFDIAN TAB ===================== -->
          <template v-if="activeTab === 'afdian'">
            <h2 style="font-size:15px;font-weight:700;color:#1c1c1e;margin:0 0 20px;">爱发电配置</h2>

            <div style="display:flex;flex-direction:column;gap:16px;">
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">标准版 Plan ID</label>
                <input
                  type="text"
                  :value="getField('afdian','basic_plan_id')"
                  @input="setField('afdian','basic_plan_id',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">专业版 Plan ID</label>
                <input
                  type="text"
                  :value="getField('afdian','premium_plan_id')"
                  @input="setField('afdian','premium_plan_id',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">User ID</label>
                <input
                  type="text"
                  :value="getField('afdian','user_id')"
                  @input="setField('afdian','user_id',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Token</label>
                <input
                  type="password"
                  :value="getField('afdian','token')"
                  @input="setField('afdian','token',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
            </div>
          </template>

          <!-- ===================== EMAIL TAB ===================== -->
          <template v-if="activeTab === 'email'">
            <h2 style="font-size:15px;font-weight:700;color:#1c1c1e;margin:0 0 20px;">邮件服务配置</h2>

            <div style="display:flex;flex-direction:column;gap:16px;">
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Resend API Key</label>
                <input
                  type="password"
                  :value="getField('email','resend_api_key')"
                  @input="setField('email','resend_api_key',($event.target as HTMLInputElement).value)"
                  placeholder="re_..."
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">发件地址</label>
                <input
                  type="text"
                  :value="getField('email','from_address')"
                  @input="setField('email','from_address',($event.target as HTMLInputElement).value)"
                  placeholder="noreply@example.com"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">前端基础 URL</label>
                <input
                  type="text"
                  :value="getField('email','frontend_base_url')"
                  @input="setField('email','frontend_base_url',($event.target as HTMLInputElement).value)"
                  placeholder="https://your-domain.com"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
            </div>
          </template>

          <!-- ===================== APP TAB ===================== -->
          <template v-if="activeTab === 'app'">
            <h2 style="font-size:15px;font-weight:700;color:#1c1c1e;margin:0 0 20px;">应用信息配置</h2>

            <div style="display:flex;flex-direction:column;gap:16px;">
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">应用名称</label>
                <input
                  type="text"
                  :value="getField('app','app_name')"
                  @input="setField('app','app_name',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>

              <div style="display:flex;align-items:center;justify-content:space-between;padding:12px;border:1px solid rgba(0,0,0,0.08);border-radius:10px;">
                <label style="font-size:13px;font-weight:600;color:#1c1c1e;">需要邀请码注册</label>
                <label style="position:relative;display:inline-block;width:44px;height:26px;cursor:pointer;">
                  <input
                    type="checkbox"
                    :checked="getField('app','require_invite_code')"
                    @change="setField('app','require_invite_code',($event.target as HTMLInputElement).checked)"
                    style="opacity:0;width:0;height:0;"
                  />
                  <span
                    :style="{
                      position:'absolute',inset:'0',borderRadius:'13px',transition:'background 0.2s',
                      background: getField('app','require_invite_code') ? '#007aff' : 'rgba(120,120,128,0.32)',
                    }"
                  />
                  <span
                    :style="{
                      position:'absolute',top:'3px',
                      left: getField('app','require_invite_code') ? '21px' : '3px',
                      width:'20px',height:'20px',borderRadius:'50%',background:'#fff',
                      boxShadow:'0 1px 4px rgba(0,0,0,0.3)',transition:'left 0.2s',
                    }"
                  />
                </label>
              </div>

              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Pro 试用弹窗标题</label>
                <input
                  type="text"
                  :value="getField('app','pro_trial_title')"
                  @input="setField('app','pro_trial_title',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">Pro 试用弹窗副标题</label>
                <input
                  type="text"
                  :value="getField('app','pro_trial_subtitle')"
                  @input="setField('app','pro_trial_subtitle',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">试用结束页标题</label>
                <input
                  type="text"
                  :value="getField('app','trial_ended_title')"
                  @input="setField('app','trial_ended_title',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
              <div>
                <label style="display:block;font-size:13px;font-weight:600;color:#1c1c1e;margin-bottom:4px;">试用结束页副标题</label>
                <input
                  type="text"
                  :value="getField('app','trial_ended_subtitle')"
                  @input="setField('app','trial_ended_subtitle',($event.target as HTMLInputElement).value)"
                  style="width:100%;box-sizing:border-box;padding:10px 12px;border-radius:8px;border:1px solid rgba(0,0,0,0.12);font-size:15px;outline:none;"
                />
              </div>
            </div>
          </template>

          <!-- Save button (every tab) -->
          <div style="margin-top:24px;">
            <button
              @click="saveSettings"
              :disabled="saving"
              style="padding:12px 24px;background:#007aff;color:#fff;border:none;border-radius:10px;font-size:15px;font-weight:600;cursor:pointer;opacity:1;transition:opacity 0.15s;"
              :style="{ opacity: saving ? 0.6 : 1 }"
            >
              {{ saving ? '保存中...' : '💾 保存' }}
            </button>
          </div>

        </div>

        <!-- Export / Import -->
        <div style="display:flex;gap:12px;margin-top:16px;">
          <button
            @click="exportSettings"
            style="flex:1;padding:12px;background:#fff;color:#007aff;border:1px solid #007aff;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;"
          >
            导出配置
          </button>
          <button
            @click="triggerImport"
            style="flex:1;padding:12px;background:#fff;color:#34c759;border:1px solid #34c759;border-radius:10px;font-size:14px;font-weight:600;cursor:pointer;"
          >
            导入配置
          </button>
          <input ref="fileInput" type="file" accept=".json" style="display:none;" @change="onFileChange" />
        </div>

      </template>
    </div>
  </div>
</template>

<style scoped>
@keyframes spin {
  to { transform: rotate(360deg); }
}
.flash-enter-active, .flash-leave-active { transition: opacity 0.3s, transform 0.3s; }
.flash-enter-from, .flash-leave-to { opacity: 0; transform: translateY(-8px); }
input:focus { border-color: #007aff !important; box-shadow: 0 0 0 3px rgba(0,122,255,0.15); }
</style>
