// frontend/src/components/SharePreviewSheet.tsx
'use client';

import { useEffect, useRef, useState } from 'react';

interface SharePreviewSheetProps {
  isOpen: boolean;
  blob: Blob | null;
  filename: string;
  onClose: () => void;
  actionColor?: string;
  stockMeta?: { name: string; action: string; confidence: number | null };
  archiveBlob?: Blob | null;
  archiveFilename?: string;
  analyzedAt?: string | null;
  onRequestArchive?: () => Promise<void>;
}

export default function SharePreviewSheet({
  isOpen,
  blob,
  filename,
  onClose,
  actionColor = '#60a5fa',
  stockMeta,
  archiveBlob,
  archiveFilename,
  analyzedAt,
  onRequestArchive,
}: SharePreviewSheetProps) {
  const [closing, setClosing] = useState(false);
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [archiveImageUrl, setArchiveImageUrl] = useState<string | null>(null);
  const [mode, setMode] = useState<'social' | 'archive'>('social');
  const [cardEntered, setCardEntered] = useState(false);
  const [swipeStartX, setSwipeStartX] = useState<number | null>(null);
  const prevBlobRef = useRef<Blob | null>(null);
  const prevArchiveBlobRef = useRef<Blob | null>(null);

  useEffect(() => {
    if (blob && blob !== prevBlobRef.current) {
      prevBlobRef.current = blob;
      const url = URL.createObjectURL(blob);
      setImageUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [blob]);

  useEffect(() => {
    if (archiveBlob && archiveBlob !== prevArchiveBlobRef.current) {
      prevArchiveBlobRef.current = archiveBlob;
      const url = URL.createObjectURL(archiveBlob);
      setArchiveImageUrl(url);
      return () => URL.revokeObjectURL(url);
    }
  }, [archiveBlob]);

  useEffect(() => {
    if (isOpen) {
      setClosing(false);
      setMode('social');
      setCardEntered(false);
      document.body.style.overflow = 'hidden';
      setTimeout(() => setCardEntered(true), 16);
    } else {
      setCardEntered(false);
      document.body.style.overflow = '';
    }
    return () => { document.body.style.overflow = ''; };
  }, [isOpen]);

  const dismiss = () => {
    setClosing(true);
    setTimeout(() => {
      setClosing(false);
      onClose();
    }, 360);
  };

  const handleDownload = async (isArchive = false) => {
    const b = isArchive ? archiveBlob : blob;
    const fn = isArchive ? (archiveFilename || filename) : filename;
    if (!b) return;

    // On mobile, prefer native share sheet (save to album / share to apps)
    if (navigator.share && navigator.canShare) {
      const file = new File([b], fn, { type: b.type });
      if (navigator.canShare({ files: [file] })) {
        try {
          await navigator.share({ files: [file] });
          return;
        } catch {
          // User cancelled or share failed — fall through to download
        }
      }
    }

    // Desktop fallback: direct download
    const a = document.createElement('a');
    a.href = URL.createObjectURL(b);
    a.download = fn;
    a.click();
  };

  const switchMode = async (next: 'social' | 'archive') => {
    if (next === mode) return;
    if (next === 'archive' && !archiveBlob && onRequestArchive) {
      await onRequestArchive();
    }
    setMode(next);
    setCardEntered(false);
    setTimeout(() => setCardEntered(true), 16);
  };

  if (!isOpen && !closing) return null;

  const activeImageUrl = mode === 'archive' ? archiveImageUrl : imageUrl;
  const hasArchiveMode = !!archiveBlob || !!onRequestArchive;

  const actionLabel =
    stockMeta?.action === 'buy' ? '买入' :
    stockMeta?.action === 'sell' ? '卖出' : '观望';

  const dateStr = analyzedAt
    ? new Date(analyzedAt).toLocaleString('zh-CN', {
        month: 'short', day: 'numeric',
        hour: '2-digit', minute: '2-digit',
      })
    : '';

  return (
    <div
      className="sps2-root"
      style={{ opacity: closing ? 0 : 1, transition: closing ? 'opacity 0.28s 0.1s ease' : 'opacity 0.22s ease' }}
      onClick={dismiss}
    >
      <div
        className={`sps2-panel${closing ? ' sps2-panel-out' : ''}`}
        onClick={e => e.stopPropagation()}
      >
        {/* Drag handle */}
        <div className="sps2-handle-zone">
          <div className="sps2-handle-pill" />
        </div>

        {/* X close button */}
        <button className="sps2-close-x" onClick={dismiss}>×</button>

        {/* Card stage with swipe + entrance */}
        <div
          className={`sps2-stage${cardEntered ? ' sps2-stage-entered' : ''}`}
          onTouchStart={(e) => setSwipeStartX(e.touches[0].clientX)}
          onTouchEnd={(e) => {
            if (swipeStartX === null || !hasArchiveMode) return;
            const delta = e.changedTouches[0].clientX - swipeStartX;
            if (Math.abs(delta) > 44) {
              switchMode(delta < 0 ? 'archive' : 'social');
            }
            setSwipeStartX(null);
          }}
        >
          <div className="sps2-glow" style={{ background: actionColor }} />
          {activeImageUrl ? (
            <img
              src={activeImageUrl}
              alt="分析卡片预览"
              className="sps2-preview-img"
              draggable={false}
            />
          ) : (
            <div className="sps2-preview-placeholder">
              <div className="sps2-preview-spinner" />
            </div>
          )}
        </div>

        {/* Dot indicators */}
        {hasArchiveMode && (
          <div className="sps2-dot-row">
            <div
              className={`sps2-dot${mode === 'social' ? ' sps2-dot-active' : ''}`}
              onClick={() => switchMode('social')}
            />
            <div
              className={`sps2-dot${mode === 'archive' ? ' sps2-dot-active' : ''}`}
              onClick={() => switchMode('archive')}
            />
          </div>
        )}

        {/* Meta strip */}
        {stockMeta && (
          <div className="sps2-meta-strip">
            <span className="sps2-meta-name">{stockMeta.name}</span>
            <span className="sps2-meta-dot">·</span>
            <span className="sps2-meta-detail" style={{ color: actionColor }}>
              {actionLabel}
            </span>
            {stockMeta.confidence != null && (
              <>
                <span className="sps2-meta-dot">·</span>
                <span className="sps2-meta-detail" style={{ color: 'rgba(255,255,255,0.55)' }}>
                  置信度 {stockMeta.confidence}%
                </span>
              </>
            )}
          </div>
        )}

        {/* Social mode actions */}
        {mode === 'social' && (
          <>
            <button
              className="sps2-primary-btn sps2-cta-shimmer"
              style={{
                background: `linear-gradient(135deg, ${actionColor}bb 0%, ${actionColor} 100%)`,
              }}
              onClick={() => handleDownload(false)}
            >
              保存到相册
            </button>
            <div className="sps2-platform-scroll">
              <div className="sps2-platform-pill">
                <span className="sps2-pill-icon">📷</span>
                <span className="sps2-pill-text">小红书发笔记</span>
              </div>
              <div className="sps2-platform-pill">
                <span className="sps2-pill-icon">💬</span>
                <span className="sps2-pill-text">发给朋友</span>
              </div>
              <div className="sps2-platform-pill">
                <span className="sps2-pill-icon">🌐</span>
                <span className="sps2-pill-text">朋友圈</span>
              </div>
            </div>
          </>
        )}

        {/* Archive mode actions */}
        {mode === 'archive' && (
          <div className="sps2-archive-zone">
            <div className="sps2-archive-seal">
              <div className="sps2-seal-accent-bar" style={{ background: actionColor }} />
              <div className="sps2-seal-content">
                <span className="sps2-seal-title">研判时间戳</span>
                <span className="sps2-seal-date">{dateStr}</span>
              </div>
              <div className="sps2-seal-lock">🔒</div>
            </div>
            <button
              className="sps2-archive-save-btn"
              onClick={() => handleDownload(true)}
            >
              保存存证图
            </button>
            <p className="sps2-archive-hint">保存后可截图或打印，作为研判时间凭据</p>
          </div>
        )}

        {/* Compliance note */}
        <div className="sps2-compliance">仅供参考，不构成投资建议</div>
      </div>
    </div>
  );
}

// frontend/components/analysis/SharePreviewSheet.vue
<script setup lang="ts">
import { ref, computed, watch, onUnmounted } from 'vue'
import { generatePredictionCardBlob, generateStatementCardBlob } from '~/lib/shareCards/index'
import type { PredictionCardParams } from '~/lib/shareCards/index'

const props = defineProps<{
  modelValue: boolean
  result: any
  symbol?: string
  market?: string
  period?: string
  tier?: string
  appName?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [value: boolean]
}>()

// ── State ──────────────────────────────────────────────────────────────────
const closing = ref(false)
const socialBlob = ref<Blob | null>(null)
const archiveBlob = ref<Blob | null>(null)
const socialImageUrl = ref<string | null>(null)
const archiveImageUrl = ref<string | null>(null)
const socialFilename = ref('')
const archiveFilename = ref('')
const mode = ref<'social' | 'archive'>('social')
const cardEntered = ref(false)
const swipeStartX = ref<number | null>(null)
const generatingSocial = ref(false)
const generatingArchive = ref(false)
const savedCardParams = ref<PredictionCardParams | null>(null)

// ── Object URL lifecycle ────────────────────────────────────────────────────
let socialUrlRef: string | null = null
let archiveUrlRef: string | null = null

watch(socialBlob, (blob) => {
  if (socialUrlRef) URL.revokeObjectURL(socialUrlRef)
  if (blob) {
    socialUrlRef = URL.createObjectURL(blob)
    socialImageUrl.value = socialUrlRef
  } else {
    socialUrlRef = null
    socialImageUrl.value = null
  }
})

watch(archiveBlob, (blob) => {
  if (archiveUrlRef) URL.revokeObjectURL(archiveUrlRef)
  if (blob) {
    archiveUrlRef = URL.createObjectURL(blob)
    archiveImageUrl.value = archiveUrlRef
  } else {
    archiveUrlRef = null
    archiveImageUrl.value = null
  }
})

onUnmounted(() => {
  if (socialUrlRef) URL.revokeObjectURL(socialUrlRef)
  if (archiveUrlRef) URL.revokeObjectURL(archiveUrlRef)
})

// ── Computed ───────────────────────────────────────────────────────────────
const action = computed<'buy' | 'sell' | 'hold'>(() => props.result?.result?.action || 'hold')
const actionLabel = computed(() =>
  action.value === 'buy' ? '看涨' : action.value === 'sell' ? '看跌' : '观望'
)
const actionColor = computed(() =>
  action.value === 'buy' ? '#EF4444' : action.value === 'sell' ? '#22C55E' : '#60A5FA'
)
const confidence = computed<number | null>(() => props.result?.result?.confidence ?? null)
const stockName = computed(() => props.result?.data?.name || props.result?.data?.symbol || '')

const activeImageUrl = computed(() =>
  mode.value === 'archive' ? archiveImageUrl.value : socialImageUrl.value
)

const analyzedAt = computed(() => {
  const r = props.result
  return r?.analyzed_at || r?.created_at || new Date().toISOString()
})

const dateStr = computed(() => {
  try {
    return new Date(analyzedAt.value).toLocaleString('zh-CN', {
      month: 'short', day: 'numeric',
      hour: '2-digit', minute: '2-digit',
    })
  } catch {
    return ''
  }
})

// ── Build card params ───────────────────────────────────────────────────────
function buildCardParams(): PredictionCardParams {
  const r = props.result
  return {
    stockName: r?.data?.name || r?.data?.symbol || '',
    stockCode: r?.data?.symbol || '',
    market: props.market || r?.data?.market || 'a',
    action: (r?.result?.action as 'buy' | 'sell' | 'hold') || 'hold',
    confidence: r?.result?.confidence ?? null,
    latestPrice: r?.data?.latest_price ?? null,
    targetPrice: r?.result?.target_price ?? null,
    stopLoss: r?.result?.stop_loss ?? null,
    opportunityGrade: r?.result?.opportunity_quality ?? null,
    reasonExcerpt: (r?.result?.reason || '').slice(0, 120),
    analyzedAt: analyzedAt.value,
    tier: props.tier || 'free',
    appName: props.appName || 'AI 股票分析',
    appBaseUrl: typeof window !== 'undefined' ? window.location.origin : undefined,
    marketDiagnosis: r?.result?.narrative?.market_diagnosis || r?.result?.market_diagnosis || '',
    opportunityAssessment: r?.result?.narrative?.opportunity_assessment || r?.result?.opportunity_assessment || '',
    riskAnalysis: r?.result?.narrative?.risk_analysis || r?.result?.risk_analysis || '',
    executionPlan: r?.result?.narrative?.execution_plan || r?.result?.execution_plan || '',
  }
}

// ── Open/close logic ────────────────────────────────────────────────────────
watch(() => props.modelValue, async (open) => {
  if (open) {
    closing.value = false
    mode.value = 'social'
    cardEntered.value = false
    socialBlob.value = null
    archiveBlob.value = null
    document.body.style.overflow = 'hidden'

    const params = buildCardParams()
    savedCardParams.value = params

    generatingSocial.value = true
    setTimeout(() => { cardEntered.value = true }, 16)

    try {
      const result = await generateStatementCardBlob(params)
      socialBlob.value = result.blob
      socialFilename.value = result.filename
    } catch (e) {
      console.error('Failed to generate statement card:', e)
    } finally {
      generatingSocial.value = false
    }
  } else {
    cardEntered.value = false
    document.body.style.overflow = ''
  }
})

function dismiss() {
  closing.value = true
  document.body.style.overflow = ''
  setTimeout(() => {
    closing.value = false
    emit('update:modelValue', false)
  }, 360)
}

// ── Mode switching ──────────────────────────────────────────────────────────
async function switchMode(next: 'social' | 'archive') {
  if (next === mode.value) return

  if (next === 'archive' && !archiveBlob.value) {
    generatingArchive.value = true
    try {
      const params = savedCardParams.value || buildCardParams()
      const result = await generatePredictionCardBlob(params)
      archiveBlob.value = result.blob
      archiveFilename.value = result.filename
    } catch (e) {
      console.error('Failed to generate prediction card:', e)
    } finally {
      generatingArchive.value = false
    }
  }

  mode.value = next
  cardEntered.value = false
  setTimeout(() => { cardEntered.value = true }, 16)
}

// ── Touch swipe ─────────────────────────────────────────────────────────────
function onTouchStart(e: TouchEvent) {
  swipeStartX.value = e.touches[0].clientX
}
function onTouchEnd(e: TouchEvent) {
  if (swipeStartX.value === null) return
  const delta = e.changedTouches[0].clientX - swipeStartX.value
  if (Math.abs(delta) > 44) {
    switchMode(delta < 0 ? 'archive' : 'social')
  }
  swipeStartX.value = null
}

// ── Save / Download ──────────────────────────────────────────────────────────
async function handleSave(isArchive = false) {
  const blob = isArchive ? archiveBlob.value : socialBlob.value
  const filename = isArchive ? archiveFilename.value : socialFilename.value
  if (!blob) return

  if (navigator.share && navigator.canShare) {
    const file = new File([blob], filename, { type: blob.type })
    if (navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({ files: [file] })
        return
      } catch {
        // user cancelled or share failed — fall through to download
      }
    }
  }

  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  a.click()
  URL.revokeObjectURL(url)
}
</script>

<template>
  <Teleport to="body">
    <div
      v-if="modelValue || closing"
      class="sps2-root"
      :style="{ opacity: closing ? 0 : 1, transition: closing ? 'opacity 0.28s 0.1s ease' : 'opacity 0.22s ease' }"
      @click="dismiss"
    >
      <div
        :class="['sps2-panel', { 'sps2-panel-out': closing }]"
        @click.stop
      >
        <!-- Drag handle -->
        <div class="sps2-handle-zone">
          <div class="sps2-handle-pill" />
        </div>

        <!-- X close button -->
        <button class="sps2-close-x" @click="dismiss">×</button>

        <!-- Card stage with swipe + entrance animation -->
        <div
          :class="['sps2-stage', { 'sps2-stage-entered': cardEntered }]"
          @touchstart="onTouchStart"
          @touchend="onTouchEnd"
        >
          <div class="sps2-glow" :style="{ background: actionColor }" />
          <img
            v-if="activeImageUrl"
            :src="activeImageUrl"
            alt="分析卡片预览"
            class="sps2-preview-img"
            draggable="false"
          />
          <div v-else class="sps2-preview-placeholder">
            <div class="sps2-preview-spinner" />
          </div>
        </div>

        <!-- Dot indicators -->
        <div class="sps2-dot-row">
          <span class="sps2-swipe-hint">‹</span>
          <div
            :class="['sps2-dot', { 'sps2-dot-active': mode === 'social' }]"
            @click="switchMode('social')"
          />
          <div
            :class="['sps2-dot', { 'sps2-dot-active': mode === 'archive' }]"
            @click="switchMode('archive')"
          />
          <span class="sps2-swipe-hint">›</span>
        </div>

        <!-- Meta strip -->
        <div class="sps2-meta-strip">
          <span class="sps2-meta-name">{{ stockName }}</span>
          <span class="sps2-meta-dot">·</span>
          <span class="sps2-meta-detail" :style="{ color: actionColor }">{{ actionLabel }}</span>
          <template v-if="confidence != null">
            <span class="sps2-meta-dot">·</span>
            <span class="sps2-meta-detail" style="color: rgba(60,60,67,0.45)">置信度 {{ confidence }}%</span>
          </template>
        </div>

        <!-- Social mode -->
        <template v-if="mode === 'social'">
          <button
            class="sps2-primary-btn sps2-cta-shimmer"
            :style="{ background: `linear-gradient(135deg, ${actionColor}bb 0%, ${actionColor} 100%)` }"
            @click="handleSave(false)"
          >
            保存到相册
          </button>
          <div class="sps2-platform-scroll">
            <div class="sps2-platform-pill" @click="handleSave(false)">
              <span class="sps2-pill-icon">📷</span>
              <span class="sps2-pill-text">小红书发笔记</span>
            </div>
            <div class="sps2-platform-pill" @click="handleSave(false)">
              <span class="sps2-pill-icon">💬</span>
              <span class="sps2-pill-text">发给朋友</span>
            </div>
            <div class="sps2-platform-pill" @click="handleSave(false)">
              <span class="sps2-pill-icon">🌐</span>
              <span class="sps2-pill-text">朋友圈</span>
            </div>
          </div>
        </template>

        <!-- Archive mode -->
        <template v-else>
          <div class="sps2-archive-zone">
            <div class="sps2-archive-seal">
              <div class="sps2-seal-accent-bar" :style="{ background: actionColor }" />
              <div class="sps2-seal-content">
                <span class="sps2-seal-title">研判时间戳</span>
                <span class="sps2-seal-date">{{ dateStr }}</span>
              </div>
              <div class="sps2-seal-lock">🔒</div>
            </div>
            <button
              class="sps2-archive-save-btn"
              :disabled="generatingArchive"
              @click="handleSave(true)"
            >
              <span v-if="generatingArchive">生成中…</span>
              <span v-else>保存存证图</span>
            </button>
            <p class="sps2-archive-hint">保存后可截图或打印，作为研判时间凭据</p>
          </div>
        </template>

        <!-- Compliance note -->
        <div class="sps2-compliance">仅供参考，不构成投资建议</div>
      </div>
    </div>
  </Teleport>
</template>
