// frontend/components/layout/DesktopSidebar.vue
<script setup lang="ts">
import { ref } from 'vue'

interface HistoryItem {
  id: string
  symbol: string
  name: string
  market: string
  action?: string
  confidence?: number
  analyzedAt?: string
  detail?: any
}

interface Props {
  appName: string
  tier: string
  tierLabel: string
  remaining: number | null
  dailyLimit: number | null
  deepRemaining?: number | null
  deepDailyLimit?: number | null
  user: any
  history: HistoryItem[]
  activePanel: string
  selectedHistoryId: string | null
  isRegisteredProTrial?: boolean
  isGuestTrial?: boolean
}

const props = withDefaults(defineProps<Props>(), {
  isRegisteredProTrial: false,
  isGuestTrial: false,
  deepRemaining: null,
  deepDailyLimit: null,
})

const emit = defineEmits<{
  'new-analysis': []
  'open-history': [item: HistoryItem]
  'upgrade': []
  'user-menu-open': []
}>()

const allOpen = ref(true)
const favOpen = ref(false)

function getActionDisplay(action?: string) {
  if (!action) return { text: '观望', color: '#f59e0b' }
  const a = action.toLowerCase()
  if (a === 'buy' || a === '买入') return { text: '买入', color: '#ef4444' }
  if (a === 'sell' || a === '卖出') return { text: '卖出', color: '#22c55e' }
  return { text: '观望', color: '#f59e0b' }
}

function formatTime(iso: string) {
  return new Date(iso).toLocaleString('zh-CN', {
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
  })
}

const isAnalyzeActive = computed(() =>
  props.activePanel === 'analyze' || props.activePanel === 'loading'
)
</script>

<template>
  <nav style="width: 240px; min-width: 240px; height: 100dvh; background: rgba(249,249,249,0.94); border-right: 0.5px solid rgba(0,0,0,0.12); display: flex; flex-direction: column; flex-shrink: 0; overflow: hidden;">

    <!-- Brand area -->
    <div style="padding: 20px 16px 14px; border-bottom: 0.5px solid rgba(0,0,0,0.08);">
      <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 6px;">
        <svg width="18" height="18" viewBox="0 0 22 22" fill="none">
          <rect x="2" y="9" width="5" height="7" rx="1.5" fill="#dc2626"/>
          <line x1="4.5" y1="6" x2="4.5" y2="9" stroke="#dc2626" stroke-width="1.5" stroke-linecap="round"/>
          <line x1="4.5" y1="16" x2="4.5" y2="19" stroke="#dc2626" stroke-width="1.5" stroke-linecap="round"/>
          <rect x="8.5" y="4" width="5" height="11" rx="1.5" fill="#34c759"/>
          <line x1="11" y1="1.5" x2="11" y2="4" stroke="#34c759" stroke-width="1.5" stroke-linecap="round"/>
          <line x1="11" y1="15" x2="11" y2="17.5" stroke="#34c759" stroke-width="1.5" stroke-linecap="round"/>
          <rect x="15" y="7" width="5" height="8" rx="1.5" fill="#dc2626"/>
          <line x1="17.5" y1="4" x2="17.5" y2="7" stroke="#dc2626" stroke-width="1.5" stroke-linecap="round"/>
          <line x1="17.5" y1="15" x2="17.5" y2="18" stroke="#dc2626" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
        <span style="font-size: 15px; font-weight: 700; color: #1c1c1e; letter-spacing: -0.3px;">{{ appName }}</span>
      </div>
      <div style="display: flex; align-items: center; gap: 6px;">
        <span
          v-if="isRegisteredProTrial || isGuestTrial"
          style="font-size: 11px; color: #8e8e93;"
        >专业版体验中</span>
        <template v-else>
          <span
            style="font-size: 11px; font-weight: 600; padding: 1px 6px; border-radius: 4px; background: rgba(0,122,255,0.1); color: #007aff;"
          >{{ tierLabel }}</span>
          <span
            v-if="remaining !== null && dailyLimit !== null"
            style="font-size: 11px; color: #8e8e93;"
          >{{ remaining }} / {{ dailyLimit }} 次</span>
          <span
            v-if="tier === 'basic' && deepRemaining !== null && deepDailyLimit !== null"
            style="font-size: 11px; color: #7c3aed;"
          >深度 {{ deepRemaining }}/{{ deepDailyLimit }}</span>
        </template>
      </div>
    </div>

    <!-- Nav buttons -->
    <div style="padding: 8px 8px 4px; flex-shrink: 0;">
      <button
        class="dt-nav-btn"
        :class="{ active: isAnalyzeActive }"
        @click="emit('new-analysis')"
      >
        <svg width="15" height="15" viewBox="0 0 20 20" fill="none">
          <circle cx="10" cy="10" r="8.5" stroke="currentColor" stroke-width="1.5"/>
          <line x1="10" y1="6.5" x2="10" y2="13.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
          <line x1="6.5" y1="10" x2="13.5" y2="10" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
        新建分析
      </button>
      <button
        v-if="tier !== 'premium'"
        class="dt-nav-btn"
        style="color: #f59e0b;"
        @click="emit('upgrade')"
      >
        <svg width="15" height="15" viewBox="0 0 20 20" fill="none">
          <polygon points="10,2 12.5,7.5 18.5,8.3 14,12.5 15.3,18.5 10,15.5 4.7,18.5 6,12.5 1.5,8.3 7.5,7.5" fill="#f59e0b"/>
        </svg>
        升级套餐
      </button>
    </div>

    <!-- History accordion (scrollable) -->
    <div style="flex: 1; overflow-y: auto; padding: 0 8px;">

      <!-- 所有分析 accordion -->
      <button class="dt-accordion-header" @click="allOpen = !allOpen">
        <span>所有分析</span>
        <svg
          class="dt-accordion-chevron"
          :class="{ open: allOpen }"
          width="12" height="12" viewBox="0 0 12 12" fill="none"
        >
          <path d="M2 4.5L6 8L10 4.5" stroke="#8e8e93" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
      </button>

      <template v-if="allOpen">
        <button
          v-for="item in history.slice(0, 50)"
          :key="item.id"
          class="dt-hist-btn"
          :class="{ active: selectedHistoryId === item.id }"
          @click="emit('open-history', item)"
        >
          <div style="display: flex; align-items: center; justify-content: space-between; gap: 6px;">
            <span style="font-size: 13px; font-weight: 600; color: #1c1c1e; flex-shrink: 0;">{{ item.symbol }}</span>
            <span
              style="font-size: 10px; font-weight: 700; padding: 1px 5px; border-radius: 4px; flex-shrink: 0;"
              :style="{ color: getActionDisplay(item.action).color, background: getActionDisplay(item.action).color + '1a' }"
            >{{ getActionDisplay(item.action).text }}</span>
          </div>
          <div style="display: flex; align-items: center; justify-content: space-between; margin-top: 2px;">
            <span style="font-size: 11px; color: #8e8e93; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; max-width: 120px;">{{ item.name }}</span>
            <span v-if="item.analyzedAt" style="font-size: 10px; color: #aeaeb2; flex-shrink: 0;">{{ formatTime(item.analyzedAt) }}</span>
          </div>
        </button>
        <div
          v-if="history.length === 0"
          style="padding: 16px 10px; font-size: 12px; color: #aeaeb2; text-align: center;"
        >
          暂无分析记录
        </div>
      </template>

      <!-- 收藏 accordion (only for logged-in users) -->
      <template v-if="user">
        <button class="dt-accordion-header" style="margin-top: 4px;" @click="favOpen = !favOpen">
          <span>收藏</span>
          <svg
            class="dt-accordion-chevron"
            :class="{ open: favOpen }"
            width="12" height="12" viewBox="0 0 12 12" fill="none"
          >
            <path d="M2 4.5L6 8L10 4.5" stroke="#8e8e93" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
          </svg>
        </button>
        <template v-if="favOpen">
          <div style="padding: 12px 10px; font-size: 12px; color: #aeaeb2; text-align: center;">
            暂无收藏
          </div>
        </template>
      </template>

    </div>

    <!-- Bottom: quota + user button -->
    <div style="padding: 16px; border-top: 0.5px solid rgba(0,0,0,0.08); display: flex; align-items: flex-end; justify-content: space-between;">
      <div>
        <div style="font-size: 10px; color: #8e8e93; margin-bottom: 2px; font-weight: 500;">今日剩余</div>
        <div style="display: flex; align-items: baseline; gap: 3px;">
          <span style="font-size: 24px; font-weight: 700; color: #1c1c1e; line-height: 1;">
            {{ remaining ?? '—' }}
          </span>
          <span v-if="dailyLimit !== null" style="font-size: 12px; color: #8e8e93;">/ {{ dailyLimit }} 次</span>
        </div>
      </div>
      <button
        style="width: 36px; height: 36px; border-radius: 50%; background: rgba(0,122,255,0.1); border: none; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; -webkit-tap-highlight-color: transparent; transition: background 0.15s;"
        @click="emit('user-menu-open')"
        @mouseenter="(e) => (e.currentTarget as HTMLElement).style.background = 'rgba(0,122,255,0.18)'"
        @mouseleave="(e) => (e.currentTarget as HTMLElement).style.background = 'rgba(0,122,255,0.1)'"
      >
        <span v-if="user" style="font-size: 14px; font-weight: 700; color: #007aff;">
          {{ (user.email || '?')[0].toUpperCase() }}
        </span>
        <svg v-else width="16" height="16" viewBox="0 0 20 20" fill="none">
          <circle cx="10" cy="7" r="3.5" stroke="#007aff" stroke-width="1.5"/>
          <path d="M3 17c0-3.314 3.134-6 7-6s7 2.686 7 6" stroke="#007aff" stroke-width="1.5" stroke-linecap="round"/>
        </svg>
      </button>
    </div>

  </nav>
</template>

<style scoped>
.dt-nav-btn {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  padding: 10px 10px;
  border: none;
  border-radius: 10px;
  background: transparent;
  cursor: pointer;
  font-size: 14px;
  font-weight: 500;
  color: #3c3c43;
  text-align: left;
  -webkit-tap-highlight-color: transparent;
  transition: background 0.1s;
}
.dt-nav-btn:hover { background: rgba(0,0,0,0.05); }
.dt-nav-btn.active { background: rgba(0,122,255,0.1); color: #007aff; }

.dt-hist-btn {
  display: block;
  width: 100%;
  padding: 8px 10px;
  border: none;
  border-radius: 8px;
  background: transparent;
  cursor: pointer;
  text-align: left;
  -webkit-tap-highlight-color: transparent;
  transition: background 0.1s;
}
.dt-hist-btn:hover { background: rgba(0,0,0,0.04); }
.dt-hist-btn.active { background: rgba(0,122,255,0.08); }

.dt-accordion-header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  width: 100%;
  padding: 8px 10px;
  border: none;
  background: transparent;
  cursor: pointer;
  font-size: 11px;
  font-weight: 700;
  color: #8e8e93;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.dt-accordion-chevron { transition: transform 0.2s; }
.dt-accordion-chevron.open { transform: rotate(180deg); }
</style>

// frontend/src/components/desktop/DesktopSidebar.tsx
'use client';

import { type FC, useState } from 'react';

interface DesktopSidebarProps {
  activePanel: 'analyze' | 'loading' | 'result';
  history: Array<{
    id: string;
    symbol: string;
    name: string;
    market: string;
    action?: string;
    confidence?: number;
    analyzedAt?: string;
    detail?: any;
  }>;
  analyzingItems: Array<{ tempId: string; symbol: string }>;
  selectedHistoryId: string | null;
  limits: { remaining: number; daily_limit: number } | null;
  effectiveTier: string;
  user: any;
  onNewAnalysis: () => void;
  onOpenHistory: (item: any) => void;
  onUpgrade: () => void;
  onUserMenuOpen: () => void;
  favorites: string[];
  appName: string;
  tierLabel: string;
  isRegisteredProTrial: boolean;
  isGuestTrial: boolean;
}

function getActionDisplay(action: string | undefined) {
  if (!action) return { text: '观望', color: '#f59e0b' };
  const a = action.toLowerCase();
  if (a === 'buy' || a === '看涨') return { text: '看涨', color: '#ef4444' };
  if (a === 'sell' || a === '看跌') return { text: '看跌', color: '#22c55e' };
  return { text: '观望', color: '#f59e0b' };
}

const DesktopSidebar: FC<DesktopSidebarProps> = ({
  activePanel, history, analyzingItems, selectedHistoryId,
  limits, effectiveTier, user,
  onNewAnalysis, onOpenHistory, onUpgrade, onUserMenuOpen,
  favorites,
  appName, tierLabel, isRegisteredProTrial, isGuestTrial
}) => {
  const [allOpen, setAllOpen] = useState(true);
  const [favOpen, setFavOpen] = useState(false);

  return (
    <nav className="dt-sidebar">
      {/* ── Brand area ── */}
      <div className="dt-sidebar-brand">
        <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
          <svg width="20" height="20" viewBox="0 0 22 22" fill="none">
            <rect x="2" y="9" width="5" height="7" rx="1.5" fill="#dc2626" />
            <line x1="4.5" y1="6" x2="4.5" y2="9" stroke="#dc2626" strokeWidth="1.5" strokeLinecap="round"/>
            <line x1="4.5" y1="16" x2="4.5" y2="19" stroke="#dc2626" strokeWidth="1.5" strokeLinecap="round"/>
            <rect x="8.5" y="4" width="5" height="11" rx="1.5" fill="#34c759" />
            <line x1="11" y1="1.5" x2="11" y2="4" stroke="#34c759" strokeWidth="1.5" strokeLinecap="round"/>
            <line x1="11" y1="15" x2="11" y2="17.5" stroke="#34c759" strokeWidth="1.5" strokeLinecap="round"/>
            <rect x="15" y="7" width="5" height="8" rx="1.5" fill="#dc2626" />
            <line x1="17.5" y1="4" x2="17.5" y2="7" stroke="#dc2626" strokeWidth="1.5" strokeLinecap="round"/>
            <line x1="17.5" y1="15" x2="17.5" y2="18" stroke="#dc2626" strokeWidth="1.5" strokeLinecap="round"/>
          </svg>
          <span style={{ fontSize: 14, fontWeight: 700, letterSpacing: '-0.2px', color: '#1c1c1e' }}>{appName}</span>
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginTop: 6 }}>
          <span style={{
            fontSize: 11, fontWeight: 500,
            color: effectiveTier === 'premium' ? '#7c3aed' : effectiveTier === 'basic' ? '#007aff' : '#8e8e93',
          }}>
            {(isRegisteredProTrial || isGuestTrial) ? '专业版体验' : tierLabel}
          </span>
          <span style={{ fontSize: 11, color: '#aeaeb2' }}>
            {limits?.remaining ?? '-'} / {limits?.daily_limit ?? '-'} 次
          </span>
        </div>
      </div>

      {/* Top nav */}
      <div style={{ flexShrink: 0, padding: '8px 0 4px' }}>
        {/* New analysis button */}
        <button
          className={`dt-nav-item${activePanel === 'analyze' || activePanel === 'loading' ? ' active' : ''}`}
          onClick={onNewAnalysis}
        >
          {/* Plus icon SVG */}
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>
          </svg>
          新建分析
        </button>

        {/* Upgrade button (for non-premium) */}
        {effectiveTier !== 'premium' && (
          <button className="dt-nav-item" onClick={onUpgrade}>
            {/* Trending up icon */}
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/>
              <polyline points="17 6 23 6 23 12"/>
            </svg>
            升级套餐
          </button>
        )}
      </div>

      {/* ── History accordion ── */}
      <div className="dt-hist-list">
        {/* "所有分析" accordion */}
        <button
          className="dt-accordion-header"
          onClick={() => setAllOpen(v => !v)}
        >
          <span>所有分析</span>
          <svg
            className={`dt-accordion-chevron${allOpen ? ' open' : ''}`}
            width="12" height="12" viewBox="0 0 24 24" fill="none"
            stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
          >
            <polyline points="6 9 12 15 18 9"/>
          </svg>
        </button>
        {allOpen && (
          <>
            {/* Analyzing placeholders */}
            {analyzingItems.map((a) => (
              <div key={a.tempId} className="dt-hist-item dt-hist-item-analyzing">
                <div className="dt-hist-item-name">{a.symbol}</div>
                <div className="dt-hist-item-row">
                  <span style={{ fontSize: 13, fontWeight: 600, color: '#007aff' }}>研判中</span>
                  <div style={{
                    width: 14, height: 14, borderRadius: '50%',
                    border: '2px solid rgba(0,122,255,0.2)', borderTopColor: '#007aff',
                    animation: 'rs-spin 0.8s linear infinite'
                  }} />
                </div>
              </div>
            ))}
            {/* History items */}
            {history.length > 0 ? (
              history.slice(0, 50).map((h) => {
                const ad = getActionDisplay(h.action);
                const isSelected = h.id === selectedHistoryId;
                const timeStr = h.analyzedAt
                  ? new Date(h.analyzedAt).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
                  : '';
                return (
                  <button
                    key={h.id}
                    className={`dt-hist-item${isSelected ? ' active' : ''}`}
                    onClick={() => onOpenHistory(h)}
                  >
                    <div className="dt-hist-item-name">{h.name || h.symbol}</div>
                    <div className="dt-hist-item-row">
                      <span className="dt-hist-item-signal" style={{ color: ad.color }}>{ad.text}</span>
                      <span className="dt-hist-item-time">{timeStr}</span>
                    </div>
                  </button>
                );
              })
            ) : (
              analyzingItems.length === 0 && (
                <div style={{ padding: '12px 10px', fontSize: 12, color: '#aeaeb2', textAlign: 'center', lineHeight: 1.6 }}>
                  暂无历史记录<br/>分析后将在此显示
                </div>
              )
            )}
          </>
        )}

        {/* "收藏" accordion — only shown for logged-in users */}
        {user && (
          <>
            <button
              className="dt-accordion-header"
              onClick={() => setFavOpen(v => !v)}
              style={{ marginTop: 4 }}
            >
              <span>收藏</span>
              <svg
                className={`dt-accordion-chevron${favOpen ? ' open' : ''}`}
                width="12" height="12" viewBox="0 0 24 24" fill="none"
                stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"
              >
                <polyline points="6 9 12 15 18 9"/>
              </svg>
            </button>
            {favOpen && (
              <>
                {favorites.length > 0 ? (
                  history.filter(h => favorites.includes(h.id)).map((h) => {
                    const ad = getActionDisplay(h.action);
                    const isSelected = h.id === selectedHistoryId;
                    const timeStr = h.analyzedAt
                      ? new Date(h.analyzedAt).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' })
                      : '';
                    return (
                      <button
                        key={h.id}
                        className={`dt-hist-item${isSelected ? ' active' : ''}`}
                        onClick={() => onOpenHistory(h)}
                      >
                        <div className="dt-hist-item-name">{h.name || h.symbol}</div>
                        <div className="dt-hist-item-row">
                          <span className="dt-hist-item-signal" style={{ color: ad.color }}>{ad.text}</span>
                          <span className="dt-hist-item-time">{timeStr}</span>
                        </div>
                      </button>
                    );
                  })
                ) : (
                  <div style={{ padding: '12px 10px', fontSize: 12, color: '#aeaeb2', textAlign: 'center', lineHeight: 1.6 }}>
                    暂无收藏
                  </div>
                )}
              </>
            )}
          </>
        )}
      </div>

      {/* Bottom: quota + avatar */}
      <div className="dt-sidebar-bottom">
        <div>
          <div style={{ fontSize: 11, fontWeight: 500, color: '#8e8e93', textTransform: 'uppercase', letterSpacing: '0.5px', marginBottom: 4 }}>
            今日剩余
          </div>
          <div style={{ fontSize: 24, fontWeight: 800, color: '#1c1c1e', letterSpacing: '-1px', lineHeight: 1 }}>
            {limits?.remaining ?? '-'}
          </div>
          <div style={{ fontSize: 12, color: '#aeaeb2', marginTop: 2 }}>
            / {limits?.daily_limit ?? '-'} 次
          </div>
        </div>
        <button
          className="dt-my-btn"
          onClick={onUserMenuOpen}
          aria-label="我的"
        >
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#3c3c43" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/>
          </svg>
        </button>
      </div>
    </nav>
  );
};

export default DesktopSidebar;
